
plugins:
  - jekyll-feed

title: iswearman Blogs
description: blog for stuff
url: https://iswearman.github.io
author: iswearman

collections:
  blog:
    output: true
    permalink: /blog/:title/

feed:
  collections:
    - blog
